version: "3"

services:
  database:
    image: "postgres:11.5"
    ports:
      - "5432:5432"
    volumes:
      - "./pg_data:/var/lib/postgresql"
    environment:
      POSTGRES_USER: pcap
      POSTGRES_PASSWORD: pcap_312b4a6b229587d831dd4a05fc83d4f7
